-- Database: GLOBALPLA Metadata version: 2 Exported: Dec 27, 2018
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5331_Receive" USING 'GCG_5331_Receive.mkd' PAGESIZE=4096 (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "ORDER_NUMBER" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "RECEIVE_DATE" DATE,
 "ACTUAL_RECEIVE_DATE" DATE,
 "QTY" NUMERIC(13,4),
 "REC_TIME" CHAR(8),
 "QTY_ORDERED" NUMERIC(13,4) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
